### ISSUE TITLE
Incorrect Detection of Rubʻ Marker as Ayah Marker Leads to Inaccurate Ayah Count

### ISSUE THREAD

**Issue by MaZED-UP** [bllfoad/ayahai#1]
Assalam Alaykum,

I would like to express my gratitude for the effort put into developing this Quran Mushaf AI model. Your dedication to this project is commendable, Jazak Allah Khaira.

After installing the necessary requirements, I ran `main.py` using these provided [Mushaf](https://mega.nz/folder/beZxmLgQ#t8yK8lebLPPTL51d_uNPkw) pages and reviewed the results. I discovered that the model incorrectly identifies a Rubʻ marker as an Ayah marker, causing the Ayah count to be incremented by 1 (right after Ayah #43 in the following sample).

![6](https://github.com/bllfoad/ayahai/assets/59477548/2c33feec-a863-4a97-897e-46abb42cb20c)

**Comment by jrahim** [comment]
Walaikumassalam!

You can filter out using the box thresholds. Maybe set a threshold of 0.6
to filter out lower confidence predictions. The rub marker prediction has a
confidence of 0.41.
